---
title: "Lab 12"
author: "Adam Hayes, Erin Omyer, Richard Park, Jasmine Sanchez"
date: "4/11/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

###Does ignoring the year change the distribution of the mean life expectancy?


```{r}
library(tidyverse)
library(gapminder)
gap <- gapminder_unfiltered

mean1952 <- gap %>%
  filter(year == 1952)%>%
  summarise(mean = mean(lifeExp))

mean2002 <- gap %>%
  filter(year == 2002)%>%
  summarise(mean = mean(lifeExp))

realDiff = mean2002 - mean1952

testGroup <- gap %>%
  filter(year == 1952 | year == 2002)

#Two-Sample Permutation Test

perm_mean <- function(perms = 1000, values, n1)
{
  # Create vector of zeroes of length "perms" to store
  # permuted mean differnces
  outputMean <- vector("double", perms)
  
  # Loop throught number of permutations
  for (i in c(1:perms))
  {
    # Randomly separate vector "values" into disjoint 
    # groups of size "n1" and "length(values) - n1" respectively
    
    vector1 <- sample(values, n1)
    vector2 <- setdiff(values, vector1)

    # Compute the sample means for the two groups from 
    # step 2
    
    firstMean <- mean(vector1)
    secondMean <- mean(vector2)
    
    # Compute the difference in sample means, store the
    # value in the vector from step 1
    
    meanDifference <- firstMean - secondMean
    
    outputMean[i] <- meanDifference
  }
  # Return new updated vector, created in step 1
  
  return(outputMean)
}
x <- seq(-4, 4, length=100)
hx <- dnorm(x)


result <- perm_mean(1000, testGroup$lifeExp, 200)
#realResult <- rnorm(result)
hist(result, col = "red", main = "Difference of Means")




```
###Is there a correlation between GDP per capita and Life Expectancy?


```{r}
#Correlation Permutation Test

perm_cor <- function(perms = 1000, x, y)
{
  # Create vector of zeroes of length "perms" to store
  # permuted mean differnces
  
  outputCor <- vector("double", perms)
  
  # Loop throught number of permutations
  for (i in c(1:perms))
  {
    # Step 2:
    # Randomly mix up the values in the vector "y"
    
    vector1 <- sample(y)

    # Compute the correlation between x and the randomly mixed
    # up y-vector. Store this value in the vector from step 1.
    
    outputCor[i] <- cor(x, vector1, method = "pearson")
  }

  # Return new updated vector, created in step 1
  return(outputCor)
}
results <- perm_cor(1000, gap$gdpPercap, gap$lifeExp)

hist(results, col = "blue", main = "Correlation" )


```

